### ISSUE TITLE
Management Docker image only in arm64 available

### ISSUE THREAD

**Issue by mrplug** [wiretrustee/wiretrustee#103]
Hello everybody,

I just noticed that all tags in the docker hub of the management image are designed for ARM64 architecture. Is this a bug or was this intended? I am unfortunately currently not able to check out the image on my Linux :(

**Comment by mlsmaycon** [comment]
Hello @mrplug, thanks for reporting this issue. 

It is a bug, the image was built against AMD64 Arch, with the correct binary, but the docker manifest used ARM as platform. 

I've pushed a fix for the 0.1.0-rc-1 tag which docker will be able to detect automatically your system and pull the correct image, however, you will have the following warning that can be **ignored**:

```shell
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested
```
I didn't change the tag 0.1.0-rc-1-amd64 because it would change its sha256 hash.

Also, I've updated the manifest creation in the PR #104 which fixes this for future releases on all tags.
