### ISSUE TITLE
Docker images not found wiretrustee/signal and wiretrustee/management

### ISSUE THREAD

**Issue by dannyfranca** [wiretrustee/wiretrustee#84]
I can't pulll docker images, looking at the hub, repository is empty, no pulls and no tags.

**Comment by braginini** [comment]
hey @dannyfranca and thank you for trying out :)
Please try using [release v0.0.8](https://github.com/wiretrustee/wiretrustee/tree/v0.0.8) docs.

We have introduced multiple architectural and deployment changes within the last month. This includes splitting up docker repos. However, we haven't had any releases yet. But within the next few weeks, we will have a major release.

**Comment by dannyfranca** [comment]
Thanks! And congratulations for this project, will be awesome.

So, with release v0.0.8 we don't need management servers or coturn? Just windows and linux binaries will work together with signal following the client configuration?

**Comment by braginini** [comment]
Thank you @dannyfranca 
v0.0.8 requires clients, signal and STUN (Coturn) to function properly.
Coturn is also used as a plan B to relay traffic.

We are hosting signal and STUN. And if you would like to just try out the system quickly you could follow client installation instructions without installing Signal and STUN. Then you could decide whether to host it or not :)

It is also possible to use public STUN servers
https://gist.github.com/mondain/b0ec1cf5f60ae726202e

The future release (~2 weeks from now) will have many more cool features and hosted UI dashboard. I will let you know personally once it out so that you could try it out.

**Comment by dannyfranca** [comment]
Nice! Ill try. Im testing alternatives to run in production very soon.

Just to know my use case, im building an application in Kubernetes Cluster including residential bare metals in different locations, so I need to deal with dynamic IPs and remote conection restriction.

So I prefer to support an open source project or even pay for an managed networking service than pay a fortune to bring it all together in a private network using AWS NAT gateways or deal with VPN complexities.

**Comment by dannyfranca** [comment]
I just tried with signal server, its impressive and easy to setup. I just used same binary as a signal server in an Ubuntu VPS.

I need to test now with coTurn. with user and pass I need to use in TURN URLs?

some_user:c29tZV9wYXNzd29yZA==@turn:stun.wiretrustee.com:3468 like in example config?

**Comment by braginini** [comment]
@dannyfranca these are just an example and are invalid.
please write to hello@wiretrustee.com I will provide you with the credentials.
